data: {
ok: false,
error: 'LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted\n' +
'Cannot run message on account: inbound external message rejected by transaction 67E94BFE6F3FFC886D0AD408EE3F1B575BBD0D6D2CE2EBC4827191F30DACFEAE:\n' +
'exitcode=35, steps=30, gas_used=0\n' +
'VM Log (truncated):\n' +
'... XCPU s3,s2\n' +
'execute EQUAL\n' +
'execute THROWIFNOT 33\n' +
'execute XCPU s4,s4\n' +
'execute EQUAL\n' +
'execute THROWIFNOT 34\n' +
'execute XCHG s4\n' +
'execute HASHSU\n' +
'execute XC2PU s0,s5,s5\n' +
'execute CHKSIGNU\n' +
'execute THROWIFNOT 35\n' +
'default exception handler, terminating vm with exit code 35\n',
code: 500
}

